fos_user:
    db_driver: orm
    firewall_name: main
    from_email:
        address: toto@gmail.com
        sender_name: toto
    service:                               
        mailer: fos_user.mailer.twig_swift 
        user_manager: sonata.user.orm.user_manager

    user_class: App\Application\Sonata\UserBundle\Entity\User
    group:
        group_class: App\Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)
